class FilterParseException(Exception):
    """
    The filters generated by the LLM could not be parsed.
    """

    def __init__(self, message, errors=None):
        super().__init__(message)
        self.message = message
        self.errors = errors


class RecommendationFilterException(Exception):
    """
    No movies fit within the filter criteria.
    """

    def __init__(self, message, errors=None):
        super().__init__(message)
        self.message = message
        self.errors = errors


class UserProfileException(Exception):
    """
    The user has not rated enough movies.
    """

    def __init__(self, message, errors=None):
        super().__init__(message)
        self.message = message
        self.errors = errors


class WatchlistEmptyException(Exception):
    """
    The user's watchlist is empty.
    """

    def __init__(self, message, errors=None):
        super().__init__(message)
        self.message = message
        self.errors = errors


class WatchlistOverlapException(Exception):
    """
    There are no movies in common across all user watchlists.
    """

    def __init__(self, message, errors=None):
        super().__init__(message)
        self.message = message
        self.errors = errors
