name: automated movie data update

on:
    workflow_dispatch:
    schedule:
        - cron: 0 4 21 * *

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo content
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10.7"

            - name: install python packages
              run: |
                  python3 -m pip install --upgrade pip
                  pip install -r backend/requirements.txt

            - name: execute scrape_movie_data.py
              env:
                  ADMIN_SECRET_KEY: ${{ secrets.ADMIN_SECRET_KEY }}
                  BACKEND_URL: ${{ secrets.BACKEND_URL }}
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
              run: python3 backend/data_processing/scrape_movie_data.py -u -c
